[package]
name = "faas-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }

[[bin]]
name = "faas-service"
path = "src/main.rs"

[[bin]]
name = "axum-example"
path = "src/axum-example.rs"
